In [1]:
'''Write a Pandas program to create and display a one-dimensional\
array-like object containing an array of data using Pandas module. '''
import pandas as pd
arr=pd.Series([1,2,3,4,5])
print(arr)
print(type(arr))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [2]:
'''Write a Pandas program to convert a Panda module Series to Python list and it's type'''
import pandas as pd
arr=pd.Series([1,2,3,4,5])
print(arr)
l1=list(arr)
print("the list is ",l1)
print("the tyep is ",type(l1))

0    1
1    2
2    3
3    4
4    5
dtype: int64
the list is  [1, 2, 3, 4, 5]
the tyep is  <class 'list'>


In [3]:
''' Write a Pandas program to add, subtract, multiple and divide two Pandas Series. 
taking Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]'''
import pandas as pd
s1=pd.Series([2, 4, 6, 8, 10])
s2=pd.Series([1, 3, 5, 7, 9])
print("series 1 is\n",s1,"\n")
print("series 2 is\n",s2)
resultant1=s1+s2
print("addition\n",resultant1)
resultant2=s1-s2
print("subtraction\n",resultant2)
resultant3=s1*s2
print("multiplication\n",resultant3)
resultant4=s1/s2
print("division\n",resultant4)



series 1 is
 0     2
1     4
2     6
3     8
4    10
dtype: int64 

series 2 is
 0    1
1    3
2    5
3    7
4    9
dtype: int64
addition
 0     3
1     7
2    11
3    15
4    19
dtype: int64
subtraction
 0    1
1    1
2    1
3    1
4    1
dtype: int64
multiplication
 0     2
1    12
2    30
3    56
4    90
dtype: int64
division
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [4]:
'''Write a Pandas program to compare the elements of the two Pandas Series. Go to the editor
taking Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]'''
import pandas as pd
s1=pd.Series([2, 4, 6, 8, 10])
s2=pd.Series([1, 3, 5, 7, 9])
print("series 1 is\n",s1,"\n")
print("series 2 is\n",s2)

print("Compare the elements of the said Series:")
l=[]
r1=s1>s2
r2=s1==s2
r3=s1<s2
print("less than\n",r1)
print("equals\n",r2)
print("gresater than\n",r3)



series 1 is
 0     2
1     4
2     6
3     8
4    10
dtype: int64 

series 2 is
 0    1
1    3
2    5
3    7
4    9
dtype: int64
Compare the elements of the said Series:
less than
 0    True
1    True
2    True
3    True
4    True
dtype: bool
equals
 0    False
1    False
2    False
3    False
4    False
dtype: bool
gresater than
 0    False
1    False
2    False
3    False
4    False
dtype: bool


In [5]:
'''Write a Pandas program to convert a dictionary to a Pandas series. 
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400'''
import pandas as pd
d={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}  # keys bydeault would be the index
ser=pd.Series(d)
ser

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [6]:
'''Write a Pandas program to convert a NumPy array to a Pandas series. 

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64'''

import numpy as np
arr=np.array([10, 20, 30, 40 ,50])
print(type(arr))
ser=pd.Series(arr)
ser

<class 'numpy.ndarray'>


0    10
1    20
2    30
3    40
4    50
dtype: int32

In [7]:
'''Write a Pandas program to change the data type of given a column or a Series. 
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64'''

ser=pd.Series([100.0,200.0,"python",300.12,400.0])
print(type(ser))
print("given series is\n",ser)
ser[2]=np.nan
print("changed series \n",ser)
s2 = pd.to_numeric(ser) 
print(s2.dtype)



<class 'pandas.core.series.Series'>
given series is
 0     100.0
1     200.0
2    python
3    300.12
4     400.0
dtype: object
changed series 
 0     100.0
1     200.0
2       NaN
3    300.12
4     400.0
dtype: object
float64


In [8]:
'''Write a Pandas program to convert the first column of a DataFrame as a Series. 
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4'''
import pandas as pd
d={"col1":[1,2,3,4,7,11],"col2":[4,5,6,9,5,0],"col3":[7,5,8,12,1,11]}
df=pd.DataFrame(d)
print(df)
print(df["col1"])
type(df["col1"])


   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


pandas.core.series.Series

In [9]:
'''Write a Pandas program to convert a given Series to an array. 
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']'''
series1=pd.Series([100,200,"python",300.12,400])
print(series1)
ar=series1.to_numpy()
ar

0       100
1       200
2    python
3    300.12
4       400
dtype: object


array([100, 200, 'python', 300.12, 400], dtype=object)

In [10]:
''' Write a Pandas program to convert Series of lists to one Series. 
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object'''
ser=pd.Series([["red","green","white"],["red","yellow"],["yellow"]])
print(ser)
l1=[]
l=list(ser)
for i in l:
    print(i)
    for j in i:
        l1.append(j)
series1=pd.Series(l1)
series1

0    [red, green, white]
1          [red, yellow]
2               [yellow]
dtype: object
['red', 'green', 'white']
['red', 'yellow']
['yellow']


0       red
1     green
2     white
3       red
4    yellow
5    yellow
dtype: object

In [11]:
'''Write a Pandas program to sort a given Series. 
Sample Output:
Original Data Series: 0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object'''

import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)

s.sort_values()

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [12]:
'''Write a Pandas program to add some data to an existing Series. 
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object'''

ser1=pd.Series(["100","200","python","300.12","400"])
print(ser1)
ser2=pd.Series(["500","php"])
s=ser1.append(ser2)
s


0       100
1       200
2    python
3    300.12
4       400
dtype: object


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

In [13]:
'''Write a Pandas program to create a subset of a given series based on value and condition. 
Sample Output:
Original Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64'''

ser=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print(ser)
subset_ser=ser.iloc[0:6]
subset_ser

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64


0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [14]:
'''Write a Pandas program to change the order of index of a given series. 
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64'''
ser=pd.Series({"A":1,"B":2,"C":3,"D":4,"E":5})
print(ser)
ser.index=["B","A","C","D","E"]
ser

A    1
B    2
C    3
D    4
E    5
dtype: int64


B    1
A    2
C    3
D    4
E    5
dtype: int64

In [15]:
'''Write a Pandas program to create the mean and standard deviation of the data of a given Series. 
Sample Output:
Original Data Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565 '''

ser=pd.Series([1,2,3,4,5,6,7,8,9,5,3])
print("mean is ",ser.mean())
print("standard eviation is ",ser.std())

mean is  4.818181818181818
standard eviation is  2.522624895547565


### problem

In [40]:
'''Write a Pandas program to get the items of a given series not present in another given series. 
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64'''
l11=[]
s1=pd.Series([1,2,3,4,5,6,7,8])
s2=pd.Series([2,4,6,8,10])

l2=list(s2)
for index, value in s1.items():
    if value not in l2:
        l11.append(value)
new_ser1=pd.Series(l11)
print("following elements of series 1 is not present in series 2\n",new_ser1)

following elements of series 1 is not present in series 2
 0    1
1    3
2    5
3    7
dtype: int64


In [17]:
'''Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series. 
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
3 8.990256
4 13.925283
5 12.056875
.... 17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]
'''
ser=pd.Series([3.000938,11.370722,14.612143,8.990256,13.925283,12.056875])
print(ser.describe())
ser.median()

count     6.000000
mean     10.659370
std       4.247050
min       3.000938
25%       9.585373
50%      11.713798
75%      13.458181
max      14.612143
dtype: float64


11.7137985

In [18]:
'''Write a Pandas program to calculate the frequency counts of each unique value of a  series. '''

ser=pd.Series([1,2,3,4,4,5,3,2,1,6,7,8,9,1,2,3,6,7,3,4,2,1,2,3,5])
ser.value_counts()


2    5
3    5
1    4
4    3
5    2
6    2
7    2
8    1
9    1
dtype: int64

In [19]:
'''Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series. 
Sample Output:
Original Series:
0 3
1 1
2 1
3 3
4 2
5 2
6 1
7 2
8 3
9 1
10 2
11 2
12 2
13 3
14 3
dtype: int64
Top 2 Freq: 2 6
3 5
1 4
dtype: int64
0 Other
1 Other
2 Other
3 Other
4 2
5 2
6 Other
7 2
8 Other
9 Other
10 2
11 2
12 2
13 Other
14 Other
dtype: object'''

ser=pd.Series([1,2,3,4,5,2,3,4,4,4,5,6,7,6,1,2,3,4,3])
print(ser,"\n")
ser=ser.where(ser != 4, "other")
    
ser

0     1
1     2
2     3
3     4
4     5
5     2
6     3
7     4
8     4
9     4
10    5
11    6
12    7
13    6
14    1
15    2
16    3
17    4
18    3
dtype: int64 



0         1
1         2
2         3
3     other
4         5
5         2
6         3
7     other
8     other
9     other
10        5
11        6
12        7
13        6
14        1
15        2
16        3
17    other
18        3
dtype: object

In [20]:
'''Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series. 
Sample Output:
Original Series:
0 1
1 9
2 8
3 6
4 9
5 7
6 1
7 1
8 1
dtype: int64
Positions of numbers that are multiples of 5:
[]'''

import numpy as np
ser=pd.Series([1,9,8,6,9,7,1,1,1,5,15,12,10])
x=np.where((ser%5==0))
print(x)

(array([ 9, 10, 12], dtype=int64),)


In [21]:
'''Write a Pandas program convert the first and last character of each word to upper case in each word of a given series. 
Sample Output:
Original Series:
0 php
1 python
2 java
3 c#
dtype: object
First and last character of each word to upper case:
0 PhP
1 PythoN
2 JavA
3 C#
dtype: object'''

ser=pd.Series(["php","python","java","c#"])
print(ser)
for index, value in ser.items():
    x=value[0].upper()+value[1:-1]+value[-1].upper()
    print(x)


0       php
1    python
2      java
3        c#
dtype: object
PhP
PythoN
JavA
C#


In [22]:
'''Write a Pandas program to calculate the number of characters in each word in a given series. 
Sample Output:
Original Series:
0 Php
1 Python
2 Java
3 C#
dtype: object
Number of characters in each word in the said series:
0 3
1 6
2 4
3 2
dtype: int64'''

ser=pd.Series(["php","python","java","c#"])
print(ser)
for index, value in ser.items():
    x=len(value)
    print(x)



0       php
1    python
2      java
3        c#
dtype: object
3
6
4
2


In [23]:
'''Write a Pandas program to compute difference of differences between consecutive numbers of a given series. 
Sample Output:
Original Series:
0 1
1 3
2 5
3 8
4 10
5 11
6 15
dtype: int64
Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]'''

ser=pd.Series([1,3,5,8,10,11,15])
l=list(ser)
print(l)
l1=[]
for  i in range(0,(len(l)+1)):
    if i==len(l)-1:
        break
    x=l[i]-l[i+1]
    l1.append(x)
print(l1)
    


[1, 3, 5, 8, 10, 11, 15]
[-2, -2, -3, -2, -1, -4]


In [24]:
'''Write a Pandas program to filter words from a given series that contain atleast two vowels. 

Original Series:
0 Red
1 Green
2 Orange
3 Pink
4 Yellow
5 White
dtype: object
Filtered words:
1 Green
2 Orange
4 Yellow
5 White'''
l=[]
c=0
ser=pd.Series(["Red","green","orange","pink","yellow","white"])
for index,value in ser.items():
    for j in value:
        if j in "aeiou":
            c=c+1
    if c>=2:
        l.append(value)
print(l)

['green', 'orange', 'pink', 'yellow', 'white']


In [25]:
'''Write a Pandas program to replace missing white spaces in a given string with the least frequent character. 
Sample Output:
Original series:
abc def abcdef icd
c 3
d 3
3
b 2
e 2
a 2
f 2
i 1
dtype: int64
abcidefiabcdefiicd'''
from collections import Counter
ser=pd.Series(["abc def abcdef icd"])
for i in ser:
    l1=Counter(i)

print(" i shows least frequent character")

ser=str(ser)

ser1=l[0].replace(" ","i")
print(ser1)

 i shows least frequent character
green
